= echo-assistant

== overview

This is a nodejs + typescript Alexa Skill interfacing with the Assistant from Google (tm). It uses the alpha sdk to talk to it,
so it may stop working with major revision changes.

[NOTE]
====
If you haven't come across Typescript before, it is just sugar on ES.next. If you compile this, it comes down to es6,
so you can just use that and start modifying it if you like.
====

It uses Amazon Polly to translate text into voice that its send to the Assistant SDK, and the resulting audio is
encoded and stored on Amazon S3 for later playback on the Amazon Echo (Alexa).

You'll need some environmental variables set up to make it run:

```bash
# Amazon Polly for TTS
AWS_POLLY_AK      # Access Key
AWS_POLLY_SECRET  # Secret

# Amazon S3 for transient audio file storage
AWS_S3_KEY        # Access Key
AWS_S3_SECRET     # Secret

# Google Assistant credentials
ASSISTANT_CLIENT_ID     # Client Id
ASSISTANT_CLIENT_SECRET # Secret

# Alexa
APP_ID    # Application ID

# Internal app vars
VOICE_CONFIG # Voice config file path (default: ./config.json)
DEBUG        # Debug key (default: 'node-assistant')
```
== installation

I use yarn, but you should be able to use npm.

so

----
npm|yarn install
export VOICE_CONFIG=./config.json
----

== building

with yarn use:
----
yarn build
----

with npm use
----
npm run copy-js && npm run tsc
----

== debugging

This uses node-debug - so set the environment variable

----
DEBUG=node-assistant node index
----

which tells it to turn debugging on.

== configuration

Edit the config.json with your own client id + secret key as per the https://developers.google.com/assistant/sdk/prototype/getting-started-other-platforms/config-dev-project-and-account[assistant website].

Then you need to cd into the target/app folder

== running
----
cd target/app
node index
----

You will get a url, which will give you a code. Enter that code on the command line and it will generate a file
and save it.

== recommended changes

You can override the location of your creds.json - it's location is in the config.json file. I would recommend
having both of them outside the folder you are using for this code.

There are a lot more configurable fields, it is based off the Java implementation of the Assistant. Go have a look at the client-config.ts
file to see what you can change.

== hotwords

The hotword stuff makes a 'ding' if it triggers. Its one of the missing things on Home that annoys me (the lack of the
audible acknowledgement). You can turn it off by leaving out the sound file. That also makes it more reliable on MacOS.

=== what else?

- I haven't tested this outside of MacOS, I will test it on a Raspberry Pi next.
- Obviously I'd love to write spec tests for this, but I was more keen on getting it actually working.
