= echo-assistant

== overview

This is a nodejs + typescript Alexa Skill interfacing with the Assistant from Google (tm). It uses the alpha sdk to talk to it,
so it may stop working with major revision changes.

[NOTE]
====
If you haven't come across Typescript before, it is just sugar on ES.next. If you compile this, it comes down to es6,
so you can just use that and start modifying it if you like.
====

It uses Amazon Polly to translate text into voice that its send to the Assistant SDK, and the resulting audio is
encoded and stored on Amazon S3 for later playback on the Amazon Echo (Alexa).

You'll need some environmental variables set up to make it run:

```bash
# Amazon Polly for TTS
AWS_POLLY_AK      # Access Key
AWS_POLLY_SECRET  # Secret

# Amazon S3 for transient audio file storage
AWS_S3_KEY        # Access Key
AWS_S3_SECRET     # Secret

# Google Assistant credentials
ASSISTANT_CLIENT_ID     # Client Id
ASSISTANT_CLIENT_SECRET # Secret

# Alexa
APP_ID    # Application ID

# Internal app vars
VOICE_CONFIG # Voice config file path (default: ./config.json)
DEBUG        # Debug key (default: 'node-assistant')
```

== Considerations

- When running this code on AWS Lambda context the node modules with bindings of this project need to be
compiled for a Linux target instead of MacOS or Windows, therefore before zipping and uploading this
to AWS you need to do that extra step (if you're not already in Linux). The way I did it was with the help of Docker, by https://medium.freecodecamp.com/escaping-lambda-function-hell-using-docker-40b187ec1e48[following this helpful article]
 I was able to compile the `node_modules` folder inside an Ubuntu container and package that for AWS.

- You can also use the `payload.json` file as a tests event on Lambda.

- When zipping the code I realized it was too big for the normal zip upload on Lambda, so I had to
upload to S3 and use the _Upload a file from Amazon S3_ option on Lambda.

== Installation

I use yarn, but you should be able to use npm.

so

----
npm|yarn install
export VOICE_CONFIG=./config.json
----

== Building

with yarn use:
----
yarn build
----

with npm use
----
npm run copy-js && npm run tsc
----

== Debugging

This uses node-debug - so set the environment variable

----
DEBUG=node-assistant node index
----

which tells it to turn debugging on.

== Configuration

Edit the config.json with your own client id + secret key as per the https://developers.google.com/assistant/sdk/prototype/getting-started-other-platforms/config-dev-project-and-account[assistant website].

Then you need to cd into the target/app folder

== Running
----
cd target/app
node index

//Or in debug mode
DEBUG=node-assistant VOICE_CONFIG=./config node index
----

You will get a url, which will give you a code. Enter that code on the command line and it will generate a file
and save it.


== thanks

To @rvowles for his amazing repo which I forked and allowed me to make this work quicker
