= echo-assistant cli

== overview

This is a nodejs + typescript version of the Assistant from Google (tm). It uses the alpha sdk to talk to it,
so it may stop working with major revision changes.

This app provides a command line interface translating text into audio using Amazon Polly, and playing the response on your speakers.

[NOTE]
====
If you haven't come across Typescript before, it is just sugar on ES.next. If you compile this, it comes down to es6,
so you can just use that and start modifying it if you like.
====

You also need to have some environmental variables set up, these include:

```
ASSISTANT_CLIENT_ID       // Assistant Client ID
ASSISTANT_CLIENT_SECRET   // Assistant Secret
AWS_POLLY_AK              //Amazon Polly Access Key
AWS_POLLY_SECRET          //Amazon Polly Secret
```

== installation

I use yarn, but you should be able to use npm.

so

----
npm|yarn install
export VOICE_CONFIG=./config.json
----

== building

with yarn use:
----
yarn build
----

with npm use
----
npm run copy-js && npm run tsc
----

== debugging

This uses node-debug - so set the environment variable

----
DEBUG=node-assistant node index
----

which tells it to turn debugging on.

== configuration

Edit the config.json with your own client id + secret key as per the https://developers.google.com/assistant/sdk/prototype/getting-started-other-platforms/config-dev-project-and-account[assistant website].

Then you need to cd into the target/app folder

== running
----
cd target/app
node index
----

You will get a url, which will give you a code. Enter that code on the command line and it will generate a file
and save it.

== recommended changes

You can override the location of your creds.json - it's location is in the config.json file. I would recommend
having both of them outside the folder you are using for this code.

There are a lot more configurable fields, it is based off the Java implementation of the Assistant. Go have a look at the client-config.ts
file to see what you can change.

=== what else?

- I haven't tested this outside of MacOS, I will test it on a Raspberry Pi next.
- node-speaker appears to have a bug on MacOS, it will occasionally seg-fault. Since this isn't a sensible deploy
 scenario, i'm not too worried.
- I want to add in support for the Google Speech API and hand-off to https://api.ai[api.ai]. It supports multiple hotwords,
 so this is sensible.
- Obviously I'd love to write spec tests for this, but I was more keen on getting it actually working.
